/*
 * generated by Xtext
 */
package org.xtextcon.xbase.smarthome;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RulesRuntimeModule extends org.xtextcon.xbase.smarthome.AbstractRulesRuntimeModule {

}
