/*
 * generated by Xtext
 */
package org.xtextcon.xbase.smarthome.ui.contentassist

import org.xtextcon.xbase.smarthome.ui.contentassist.AbstractRulesProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RulesProposalProvider extends AbstractRulesProposalProvider {
}
