/*
* generated by Xtext
*/
package org.xtextcon.xbase.smarthome;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RulesUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtextcon.xbase.smarthome.ui.internal.RulesActivator.getInstance().getInjector("org.xtextcon.xbase.smarthome.Rules");
	}
	
}
