/**
 * generated by Xtext
 */
package org.xtextcon.xbase.smarthome.validation;

import org.xtextcon.xbase.smarthome.validation.AbstractRulesValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class RulesValidator extends AbstractRulesValidator {
}
