/*
 * generated by Xtext
 */
package org.xtextcon.xbase.smarthome.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RulesUiModule extends org.xtextcon.xbase.smarthome.ui.AbstractRulesUiModule {
	public RulesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
