/*
* generated by Xtext
*/
package org.xtextcon.xbase.smarthome.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RulesAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtextcon/xbase/smarthome/parser/antlr/internal/InternalRules.tokens");
	}
}
